namespace Kenedia.Modules.BuildsManager.Enums
{
    public enum Icons
    {
        Bug,
        Refresh,
        Template,
        Template_White,
        Helmet,
        Helmet_White,
        Cog,
        Cog_White,
        Undo,
        Undo_White,
        Checkmark_White,
        Checkmark_Color,
        Checkmark_Highlight,
        Stop_White,
        Stop_Color,
        Stop_Highlight,
        Search,
        Search_Highlight,
        Edit_Feather,
        Edit_Feather_Highlight,
        Edit_Feather_Pressed,
        Mouse,
        Lock_Locked,
        SingleSpinner,
    }
}