//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.BuildsManager.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.BuildsManager.Strings.common", typeof(common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        internal static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Damage.
        /// </summary>
        internal static string ConditionDamage {
            get {
                return ResourceManager.GetString("ConditionDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        internal static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferocity.
        /// </summary>
        internal static string Ferocity {
            get {
                return ResourceManager.GetString("Ferocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        internal static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click to select Stat/Upgrade
        ///Alt + Right Click to select Weapon
        ///Right Click to copy Stat/Upgrade Name.
        /// </summary>
        internal static string GearTab_Tips {
            get {
                return ResourceManager.GetString("GearTab_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Power.
        /// </summary>
        internal static string HealingPower {
            get {
                return ResourceManager.GetString("HealingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision.
        /// </summary>
        internal static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code.
        /// </summary>
        internal static string TemplateCode {
            get {
                return ResourceManager.GetString("TemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toughness.
        /// </summary>
        internal static string Toughness {
            get {
                return ResourceManager.GetString("Toughness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        internal static string Vitality {
            get {
                return ResourceManager.GetString("Vitality", resourceCulture);
            }
        }
    }
}
